batch_size: 32  # total: 4*6
iters: 99999999999   #无用参数，已经修改为根据训练数据集大小自适应变化
max_epoch: 300

train_dataset:
  type: Dataset
  dataset_root: ../../BlueFaceDataX2_PP
  num_classes: 9
  mode: train
  train_path: ../../BlueFaceDataX2_PP/train.txt
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.75
      max_scale_factor: 1.25
      scale_step_size: 0.05
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize

val_dataset:
  type: Dataset
  dataset_root: ../../BlueFaceDataX2_PP
  num_classes: 9
  mode: val
  val_path: ../../BlueFaceDataX2_PP/val.txt
  transforms:
    - type: Normalize
      mean: [ 0.46962251, 0.4464104, 0.40718787 ]
      std: [ 0.27469736, 0.27012361, 0.28515933 ]

optimizer:
  type: AdamW
  weight_decay: 1.0e-3

lr_scheduler:
  type: CosineAnnealingDecay
  learning_rate: 0.0002
  eta_min: 5.0e-6
  warmup_start_lr: 0.0001

loss:
  types:
    - type: OhemCrossEntropyLoss
#    - type: MixedLoss
#      losses:
#        - type: CrossEntropyLoss
#        - type: LovaszSoftmaxLoss
#      coef: [0.8, 0.2]
  coef: [1]


model:
  type: PPMobileSeg
  num_classes: 9
  backbone:
    type: MobileSeg_Base
    inj_type: AAMSx8
    out_feat_chs: [64, 128, 192]
    pretrained: ../premodels/pp_mobileseg_base.pdparams
  upsample: vim  # During exportation, you need to change it to vim for using VIM
#  upsample: intepolate  # During exportation, you need to change it to vim for using VIM




