_base_: '../_base_/blueface.yml'

batch_size: 12  # total: 4*6
max_epoch: 300

train_dataset:
  dataset_root: ../../BlueFaceDataX2_PP
  train_path: ../../BlueFaceDataX2_PP/train.txt
  num_classes: 9
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.75
      max_scale_factor: 1.25
      scale_step_size: 0.05
    - type: RandomPaddingCrop
      crop_size: [224, 224]

val_dataset:
  dataset_root: ../../BlueFaceDataX2_PP
  val_path: ../../BlueFaceDataX2_PP/val.txt
  num_classes: 9

lr_scheduler:
  type: CosineAnnealingDecay
  learning_rate: 0.0001
  eta_min: 5.0e-6
  warmup_start_lr: 0.00005

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
  coef: [1]


model:
  type: PPMobileSeg
  num_classes: 9
  backbone:
    type: MobileSeg_Tiny
    inj_type: AAM
    out_feat_chs: [32, 64, 128]
    pretrained: ../premodels/pp_mobileseg_tiny.pdparams
#  upsample: vim  # During exportation, you need to change it to vim for using VIM
  upsample: intepolate  # During exportation, you need to change it to vim for using VIM




