iters: 99999999999   #无用参数，已经修改为根据训练数据集大小自适应变化
max_epoch: 350
batch_size: 32  # total: 4*6

num_classes: &num_classes 9
dataset_root: &dataset_root ../../BlueFaceDataX2_PP
train_path: &train_path ../../BlueFaceDataX2_PP/train.txt
val_path: &val_path ../../BlueFaceDataX2_PP/val.txt

train_dataset:
  type: Dataset
  dataset_root: *dataset_root
  num_classes: *num_classes
  mode: train
  train_path: *train_path
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.75
      max_scale_factor: 1.25
      scale_step_size: 0.05
    - type: RandomPaddingCrop
      im_padding_value: 0.0
      label_padding_value: 0
      loop_times: 2
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
      mean: [ 0.46962251, 0.4464104, 0.40718787 ]
      std: [ 0.27469736, 0.27012361, 0.28515933 ]

val_dataset:
  type: Dataset
  dataset_root: *dataset_root
  num_classes: *num_classes
  mode: val
  val_path: *val_path
  transforms:
    - type: Normalize
      mean: [ 0.46962251, 0.4464104, 0.40718787 ]
      std: [ 0.27469736, 0.27012361, 0.28515933 ]

optimizer:
  type: AdamW
  weight_decay: 1.0e-3

lr_scheduler:
  type: CosineAnnealingDecay
  learning_rate: 0.0002
  eta_min: 5.0e-6
  warmup_start_lr: 0.0001

#loss:
#  types:
#    - type: OhemCrossEntropyLoss
#  coef: [1]
loss:
  types:
    - type: MixedLoss
      losses:
        - type: OhemCrossEntropyLoss
        - type: LogCosDiceLoss
      coef: [1.0, 3.0]
  coef: [1]

model:
  type: SeaFormerSeg
  backbone: 
    type: SeaFormer_tiny
    pretrained: ../premodels/seaformer_tiny_imagenet_pretrained.pdparams
  head_channels: 96
  embed_dims: [64, 96]
  is_dw: True
  dropout_ratio: 0.1
  align_corners: False
  input_transform: 'multiple_select'