_base_: '../_base_/blueface.yml'

batch_size: 12  # total: 4*6
max_epoch: 300

train_dataset:
  dataset_root: ../../BlueFaceDataX2_PP
  train_path: ../../BlueFaceDataX2_PP/train.txt
  num_classes: 9
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.75
      max_scale_factor: 1.25
      scale_step_size: 0.05
    - type: RandomPaddingCrop
      crop_size: [512, 512]

val_dataset:
  dataset_root: ../../BlueFaceDataX2_PP
  val_path: ../../BlueFaceDataX2_PP/val.txt
  num_classes: 9

lr_scheduler:
  type: CosineAnnealingDecay
  learning_rate: 0.0001
  eta_min: 5.0e-6
  warmup_start_lr: 0.00005

loss:
  types:
    - type: OhemCrossEntropyLoss
    - type: OhemCrossEntropyLoss
    - type: OhemCrossEntropyLoss
  coef: [1, 1, 1]


model:
  type: PPLiteSeg
  backbone:
    type: STDC1
    pretrained: ../premodels/PP_STDCNet1.pdparams
  arm_out_chs: [32, 64, 128]
  seg_head_inter_chs: [32, 64, 64]
