batch_size: 32  # total: 4*6
iters: 99999999999   #无用参数，已经修改为根据训练数据集大小自适应变化
max_epoch: 50

train_dataset:
  type: Dataset
  dataset_root: ..\..\BlueFaceDataX2_PP
  num_classes: 9
  mode: train
  train_path: ..\..\BlueFaceDataX2_PP\train.txt
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.75
      max_scale_factor: 1.25
      scale_step_size: 0.1
    - type: RandomPaddingCrop
      crop_size: [224, 224]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize

val_dataset:
  type: Dataset
  dataset_root: ..\..\BlueFaceDataX2_PP
  num_classes: 9
  mode: val
  val_path: ..\..\BlueFaceDataX2_PP\val.txt
  transforms:
    - type: Normalize

optimizer:
  type: AdamW
  weight_decay: 1.0e-3

lr_scheduler:
  type: CosineAnnealingDecay
  learning_rate: 0.0001
#  T_max: 800
  eta_min: 5.0e-6
#  warmup_iters: 80
  warmup_start_lr: 0.00001
#lr_scheduler:
#  type: PolynomialDecay
#  learning_rate: 0.0001
#  end_lr: 5.0e-6
#  power: 0.9
#  warmup_iters: 100
#  warmup_start_lr: 1.0e-5

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [ 0.8, 0.2 ]
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
#    - type: OhemCrossEntropyLoss
#      min_kept: 250000   # batch_size * 960 * 720 // 16
#    - type: OhemCrossEntropyLoss
#      min_kept: 250000
#    - type: OhemCrossEntropyLoss
#      min_kept: 250000
  coef: [1, 1, 1]

model:
  type: PPLiteSeg
  backbone:
    type: STDC1
    pretrained: ..\premodels\PP_STDCNet1.pdparams
  arm_out_chs: [32, 64, 128]
  seg_head_inter_chs: [32, 64, 64]
